name: Update aboutme site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update personal site
      run: |
        cd ..
        git clone https://github.com/rprtr258/rprtr258.github.io
        cp data-science/README.md rprtr258.github.io/mlprojects.html
    - name: Commit files
      run: |
        cd ../rprtr258.github.io
        git config --local user.email "action@github.com"
        git config --local user.name "rprtr258/data-science GitHub Action"
        git add .
        git commit -m "Update mlprojects page" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SITE_GITHUB_TOKEN }}
        directory: /home/runner/work/data-science/rprtr258.github.io
        repository: rprtr258/rprtr258.github.io
