name: Update aboutme site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone site repository
      run: |
        cd ..
        git clone https://github.com/rprtr258/rprtr258.github.io
    - name: Update personal site
      run: |
        cd ..
        sudo npm install showdown -g
        showdown makehtml -i data-science/README.md -o rprtr258.github.io/mlprojects.html
    - name: Commit files
      run: |
        cd ../rprtr258.github.io
        COMMIT_MESSAGE="Update mlprojects page on $(date +'%Y-%m-%d %H:%M:%S')"
        git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo "$COMMIT_MESSAGE"
        git config --local user.email "action@github.com"
        git config --local user.name "rprtr258/data-science GitHub Action"
        git commit -m "$COMMIT_MESSAGE" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SITE_GITHUB_TOKEN }}
        directory: /home/runner/work/data-science/rprtr258.github.io
        repository: rprtr258/rprtr258.github.io
